/**
 * Mapa de subcategorias por comando — gerado por scripts/extract-taxonomy.js
 * a partir da curadoria manual que existia no menu.js hardcoded.
 *
 * Fonte transitória para o LEGADO. Comandos novos devem declarar
 * `subcategory` no próprio arquivo em vez de adicionar aqui.
 *
 *   token (nome ou alias, lowercase) -> título da subcategoria
 */
module.exports = {
    "abrirgrupo": "⚙️ EDIÇÃO & SEGURANÇA AVANÇADA",
    "aceitar": "🛡️ ADMINISTRAÇÃO & SEGURANÇA",
    "acoes": "💰 ECONOMIA, BANCO & BOLSA",
    "adivinhar": "🎲 DIVERSÃO & JOGOS",
    "adm": "🛡️ ADMINISTRAÇÃO & SEGURANÇA",
    "admin": "ℹ️ INFORMAÇÕES RÁPIDAS & ATALHOS",
    "adotar": "🏆 PERFIL & ECONOMIA",
    "agendarmensagem": "🛡️ ADMINISTRAÇÃO & SEGURANÇA",
    "aliases-admin": "⚙️ EDIÇÃO & SEGURANÇA AVANÇADA",
    "aliases-all": "👑 DONOS, VPS & ALUGUEL",
    "aliases-aluguel": "⏱️ GESTÃO DE PRAZOS PIX",
    "aliases-arquivos": "📖 LIVROS & MATERIAIS EM PDF",
    "aliases-calc": "📐 ARITMÉTICA & EXPRESSÕES",
    "aliases-config": "🛡️ SEGURANÇA, GRUPO & WALLPAPERS",
    "aliases-dev": "🛠️ FERRAMENTAS DEV & CRIPTOGRAFIA",
    "aliases-dono": "🎖️ SERVIDOR VPS, COMANDOS & SEGURANÇA",
    "aliases-eco": "🎰 CASSINO, LOTERIAS & APOSTAS",
    "aliases-fun": "♟️ TABULEIRO & CLÁSSICOS",
    "aliases-interacao": "💖 AFETO & CARINHO",
    "aliases-media": "🎨 FILTROS, CANVAS & FIGURINHAS",
    "aliases-pesquisa": "🌐 UTILITÁRIOS COTIDIANOS",
    "aliases-rede": "🏓 CONEXÃO & LATÊNCIA",
    "aliases-rpg": "🧙 CLASSES, PETS, MERCADO & GUILDAS",
    "aluguel": "👑 DONOS, VPS & ALUGUEL",
    "amigosecreto": "🎮 JOGOS INTERATIVOS NO CHAT",
    "anagrama": "🎮 JOGOS INTERATIVOS NO CHAT",
    "anime": "🔍 PESQUISA, IA & UTILITÁRIOS",
    "animesazonal": "🔍 PESQUISA, IA & UTILITÁRIOS",
    "antifake": "🛡️ ADMINISTRAÇÃO & SEGURANÇA",
    "antilink": "🛡️ ADMINISTRAÇÃO & SEGURANÇA",
    "antilinkstatus": "🛡️ ADMINISTRAÇÃO & SEGURANÇA",
    "antispamlink": "🛡️ ADMINISTRAÇÃO & SEGURANÇA",
    "api": "👨‍💻 DEV HUB & FERRAMENTAS",
    "arcanjo": "👑 RELÍQUIAS, MANDAMENTOS & ARCANJOS",
    "arena": "🏹 CAÇA, MASMORRAS & BATALHAS",
    "ascensao": "👑 RELÍQUIAS, MANDAMENTOS & ARCANJOS",
    "atk": "🏹 CAÇA, MASMORRAS & BATALHAS",
    "b64": "👨‍💻 DEV HUB & FERRAMENTAS",
    "backup": "🎖️ SERVIDOR VPS, COMANDOS & SEGURANÇA",
    "ban": "🛡️ ADMINISTRAÇÃO & SEGURANÇA",
    "bancmd": "👑 DONOS, VPS & ALUGUEL",
    "banco": "💰 ECONOMIA, BANCO & BOLSA",
    "banlist": "🛡️ ADMINISTRAÇÃO & SEGURANÇA",
    "batalhanaval": "🎲 DIVERSÃO & JOGOS",
    "batalhar": "🏹 CAÇA, MASMORRAS & BATALHAS",
    "beijotapamatar": "🎮 JOGOS INTERATIVOS NO CHAT",
    "bencao": "⚔️ RPG & COMBATES",
    "bingo": "🏆 PERFIL & ECONOMIA",
    "bioma": "🏹 CAÇA, MASMORRAS & BATALHAS",
    "blackjack": "🎰 CASSINO, LOTERIAS & APOSTAS",
    "blur": "🎨 FILTROS, CANVAS & FIGURINHAS",
    "boladeouro": "🎲 DIVERSÃO & JOGOS",
    "bolsafam": "💰 ECONOMIA, BANCO & BOLSA",
    "boss": "⚔️ RPG & COMBATES",
    "botclose": "🎖️ SERVIDOR VPS, COMANDOS & SEGURANÇA",
    "botopen": "🎖️ SERVIDOR VPS, COMANDOS & SEGURANÇA",
    "botstats": "🏓 CONEXÃO & LATÊNCIA",
    "buy": "🏆 PERFIL & ECONOMIA",
    "cacaaotesouro": "🎰 CASSINO, LOTERIAS & APOSTAS",
    "calculadoradeamor": "🎮 JOGOS INTERATIVOS NO CHAT",
    "calculoidade": "🔍 PESQUISA, IA & UTILITÁRIOS",
    "caraoucoroa": "🎰 CASSINO, LOTERIAS & APOSTAS",
    "cassino": "🎰 CASSINO, LOTERIAS & APOSTAS",
    "cep": "🔍 PESQUISA, IA & UTILITÁRIOS",
    "charada": "🎮 JOGOS INTERATIVOS NO CHAT",
    "chorar": "💖 AFETO & CARINHO",
    "circle": "🎨 FILTROS, CANVAS & FIGURINHAS",
    "clash": "🎲 DIVERSÃO & JOGOS",
    "classe": "🧙 CLASSES, PETS, MERCADO & GUILDAS",
    "classeshop": "🧙 CLASSES, PETS, MERCADO & GUILDAS",
    "clear": "🛡️ ADMINISTRAÇÃO & SEGURANÇA",
    "clima": "🔍 PESQUISA, IA & UTILITÁRIOS",
    "cofre": "🏆 PERFIL & ECONOMIA",
    "cofregrupo": "💰 ECONOMIA, BANCO & BOLSA",
    "coliseu": "⚔️ RPG & COMBATES",
    "color": "👨‍💻 DEV HUB & FERRAMENTAS",
    "colorpalette": "👨‍💻 DEV HUB & FERRAMENTAS",
    "comandocount": "🔍 PESQUISA, IA & UTILITÁRIOS",
    "comprarclasse": "⚔️ RPG & COMBATES",
    "conexao": "📊 STATUS & CLASSIFICAÇÃO",
    "config": "🛡️ SEGURANÇA, GRUPO & WALLPAPERS",
    "conquistas": "🎮 JOGOS INTERATIVOS NO CHAT",
    "cotacao": "🌐 UTILITÁRIOS COTIDIANOS",
    "cp": "🏹 CAÇA, MASMORRAS & BATALHAS",
    "craft": "🧙 CLASSES, PETS, MERCADO & GUILDAS",
    "crime": "💰 ECONOMIA, BANCO & BOLSA",
    "cripto": "🏆 PERFIL & ECONOMIA",
    "cron": "👨‍💻 DEV HUB & FERRAMENTAS",
    "curar": "🏹 CAÇA, MASMORRAS & BATALHAS",
    "curar-max": "🏹 CAÇA, MASMORRAS & BATALHAS",
    "curlemu": "👨‍💻 DEV HUB & FERRAMENTAS",
    "daily": "💰 ECONOMIA, BANCO & BOLSA",
    "dama": "♟️ TABULEIRO & CLÁSSICOS",
    "dancar": "💖 AFETO & CARINHO",
    "dardo": "🎮 JOGOS INTERATIVOS NO CHAT",
    "ddd": "🔍 PESQUISA, IA & UTILITÁRIOS",
    "deldono": "👑 DONOS, VPS & ALUGUEL",
    "despertar": "⚔️ RPG & COMBATES",
    "device": "📊 STATUS & CLASSIFICAÇÃO",
    "dicionario": "🔍 PESQUISA, IA & UTILITÁRIOS",
    "dns": "👨‍💻 DEV HUB & FERRAMENTAS",
    "dono": "🎖️ SERVIDOR VPS, COMANDOS & SEGURANÇA",
    "dossie": "🏆 PERFIL & ECONOMIA",
    "dossiegrupo": "🔍 PESQUISA, IA & UTILITÁRIOS",
    "duelo": "⚔️ RPG & COMBATES",
    "dueloaposta": "🏆 PERFIL & ECONOMIA",
    "duelofrase": "🎮 JOGOS INTERATIVOS NO CHAT",
    "dungeon": "🏹 CAÇA, MASMORRAS & BATALHAS",
    "eco": "ℹ️ INFORMAÇÕES RÁPIDAS & ATALHOS",
    "emojimix": "📥 DOWNLOADS, MÍDIAS & FILTROS",
    "emprestimo": "🏆 PERFIL & ECONOMIA",
    "encurtar": "👨‍💻 DEV HUB & FERRAMENTAS",
    "enquete": "🛡️ ADMINISTRAÇÃO & SEGURANÇA",
    "entrar": "🎖️ SERVIDOR VPS, COMANDOS & SEGURANÇA",
    "evoluirpet": "🧙 CLASSES, PETS, MERCADO & GUILDAS",
    "explorar": "🏹 CAÇA, MASMORRAS & BATALHAS",
    "extrato": "💰 ECONOMIA, BANCO & BOLSA",
    "fakeuser": "🛠️ FERRAMENTAS DEV & CRIPTOGRAFIA",
    "familia": "📊 STATUS & CLASSIFICAÇÃO",
    "familiar": "⚔️ RPG & COMBATES",
    "farmpv": "🎖️ SERVIDOR VPS, COMANDOS & SEGURANÇA",
    "fatosanime": "🌸 ANIMES, MANGÁS, FILMES & MÚSICAS",
    "fechargrupo": "🛡️ ADMINISTRAÇÃO & SEGURANÇA",
    "ferreiro": "⚔️ RPG & COMBATES",
    "fig": "🎨 FILTROS, CANVAS & FIGURINHAS",
    "figtexto": "📥 DOWNLOADS, MÍDIAS & FILTROS",
    "filme": "🔍 PESQUISA, IA & UTILITÁRIOS",
    "forca": "♟️ TABULEIRO & CLÁSSICOS",
    "forjar": "🏹 CAÇA, MASMORRAS & BATALHAS",
    "fullcounter": "👑 RELÍQUIAS, MANDAMENTOS & ARCANJOS",
    "gado": "♟️ TABULEIRO & CLÁSSICOS",
    "gaymaster": "♟️ TABULEIRO & CLÁSSICOS",
    "gerarsenha": "👨‍💻 DEV HUB & FERRAMENTAS",
    "gif": "🎨 FILTROS, CANVAS & FIGURINHAS",
    "github": "👨‍💻 DEV HUB & FERRAMENTAS",
    "google": "🔍 PESQUISA, IA & UTILITÁRIOS",
    "gpt": "🔍 PESQUISA, IA & UTILITÁRIOS",
    "grimorio": "🏹 CAÇA, MASMORRAS & BATALHAS",
    "grupos": "🎖️ SERVIDOR VPS, COMANDOS & SEGURANÇA",
    "gruposettings": "🛡️ ADMINISTRAÇÃO & SEGURANÇA",
    "guilda": "⚔️ RPG & COMBATES",
    "hash": "👨‍💻 DEV HUB & FERRAMENTAS",
    "headers": "👨‍💻 DEV HUB & FERRAMENTAS",
    "hidetag": "👥 GESTÃO DE MEMBROS & MODERAÇÃO",
    "httpstatus": "👨‍💻 DEV HUB & FERRAMENTAS",
    "hunt": "🏹 CAÇA, MASMORRAS & BATALHAS",
    "ia": "🌐 UTILITÁRIOS COTIDIANOS",
    "iaver": "🔍 PESQUISA, IA & UTILITÁRIOS",
    "inativos": "👥 GESTÃO DE MEMBROS & MODERAÇÃO",
    "infogrupo": "👥 GESTÃO DE MEMBROS & MODERAÇÃO",
    "insta": "📥 DOWNLOADS, MÍDIAS & FILTROS",
    "inv": "🧙 CLASSES, PETS, MERCADO & GUILDAS",
    "invert": "🎨 FILTROS, CANVAS & FIGURINHAS",
    "investir": "💰 ECONOMIA, BANCO & BOLSA",
    "ipinfo": "👨‍💻 DEV HUB & FERRAMENTAS",
    "jogodobicho": "🏆 PERFIL & ECONOMIA",
    "jornal": "📥 DOWNLOADS, MÍDIAS & FILTROS",
    "json": "👨‍💻 DEV HUB & FERRAMENTAS",
    "jwt": "🛠️ FERRAMENTAS DEV & CRIPTOGRAFIA",
    "kick": "🛡️ ADMINISTRAÇÃO & SEGURANÇA",
    "kwai": "📥 DOWNLOADS, MÍDIAS & FILTROS",
    "lapide": "📥 DOWNLOADS, MÍDIAS & FILTROS",
    "leave": "🛡️ ADMINISTRAÇÃO & SEGURANÇA",
    "leilao": "🧙 CLASSES, PETS, MERCADO & GUILDAS",
    "lendaria": "⚔️ RPG & COMBATES",
    "letra": "🔍 PESQUISA, IA & UTILITÁRIOS",
    "limparfantasmas": "👥 GESTÃO DE MEMBROS & MODERAÇÃO",
    "link": "⚙️ EDIÇÃO & SEGURANÇA AVANÇADA",
    "listaregras": "🛡️ ADMINISTRAÇÃO & SEGURANÇA",
    "locknick": "🛡️ ADMINISTRAÇÃO & SEGURANÇA",
    "lootshop": "⚔️ RPG & COMBATES",
    "lostvayne": "👑 RELÍQUIAS, MANDAMENTOS & ARCANJOS",
    "lotofacil": "🏆 PERFIL & ECONOMIA",
    "magias": "🏹 CAÇA, MASMORRAS & BATALHAS",
    "mandamento": "👑 RELÍQUIAS, MANDAMENTOS & ARCANJOS",
    "manga": "🔍 PESQUISA, IA & UTILITÁRIOS",
    "manutencao": "🎖️ SERVIDOR VPS, COMANDOS & SEGURANÇA",
    "market": "🧙 CLASSES, PETS, MERCADO & GUILDAS",
    "masmorra": "🏹 CAÇA, MASMORRAS & BATALHAS",
    "masmorrainfinita": "⚔️ RPG & COMBATES",
    "media": "📥 DOWNLOADS, MÍDIAS & FILTROS",
    "megasena": "🏆 PERFIL & ECONOMIA",
    "meme": "📥 DOWNLOADS, MÍDIAS & FILTROS",
    "memefrase": "🎮 JOGOS INTERATIVOS NO CHAT",
    "memoria": "🎲 DIVERSÃO & JOGOS",
    "menu": "🧙 CLASSES, PETS, MERCADO & GUILDAS",
    "mercado": "🧙 CLASSES, PETS, MERCADO & GUILDAS",
    "metrics": "👑 DONOS, VPS & ALUGUEL",
    "minerar": "💰 ECONOMIA, BANCO & BOLSA",
    "missao": "⚔️ RPG & COMBATES",
    "mob": "⚔️ RPG & COMBATES",
    "mundo": "⚔️ RPG & COMBATES",
    "nobg": "🎨 FILTROS, CANVAS & FIGURINHAS",
    "npm": "👨‍💻 DEV HUB & FERRAMENTAS",
    "ocr": "🎨 FILTROS, CANVAS & FIGURINHAS",
    "patrocinar": "🏆 PERFIL & ECONOMIA",
    "pay": "🏆 PERFIL & ECONOMIA",
    "perfil": "ℹ️ INFORMAÇÕES RÁPIDAS & ATALHOS",
    "perguntadodia": "🎮 JOGOS INTERATIVOS NO CHAT",
    "pesadelo": "🏹 CAÇA, MASMORRAS & BATALHAS",
    "pescar": "💰 ECONOMIA, BANCO & BOLSA",
    "pet": "⚔️ RPG & COMBATES",
    "ping": "🏓 CONEXÃO & LATÊNCIA",
    "pingrede": "🏓 CONEXÃO & LATÊNCIA",
    "pingvps": "🏓 CONEXÃO & LATÊNCIA",
    "pinterest": "📥 DOWNLOADS, MÍDIAS & FILTROS",
    "pixelar": "🎨 FILTROS, CANVAS & FIGURINHAS",
    "play": "📥 DOWNLOADS, MÍDIAS & FILTROS",
    "pocao": "🧙 CLASSES, PETS, MERCADO & GUILDAS",
    "ppt": "♟️ TABULEIRO & CLÁSSICOS",
    "presentear": "🏆 PERFIL & ECONOMIA",
    "promovertodos": "👥 GESTÃO DE MEMBROS & MODERAÇÃO",
    "purgatorio": "🏹 CAÇA, MASMORRAS & BATALHAS",
    "qrcode": "👨‍💻 DEV HUB & FERRAMENTAS",
    "qualmusica": "🎮 JOGOS INTERATIVOS NO CHAT",
    "qualpersonagem": "🎮 JOGOS INTERATIVOS NO CHAT",
    "quiz": "♟️ TABULEIRO & CLÁSSICOS",
    "quizanime": "🎲 DIVERSÃO & JOGOS",
    "quote": "📥 DOWNLOADS, MÍDIAS & FILTROS",
    "racha": "🎲 DIVERSÃO & JOGOS",
    "raid": "⚔️ RPG & COMBATES",
    "rank": "📊 STATUS & CLASSIFICAÇÃO",
    "rankcp": "🏹 CAÇA, MASMORRAS & BATALHAS",
    "rankglobal": "📊 STATUS & CLASSIFICAÇÃO",
    "rankslayer": "🏹 CAÇA, MASMORRAS & BATALHAS",
    "raspadinha": "🎰 CASSINO, LOTERIAS & APOSTAS",
    "rastreio": "🔍 PESQUISA, IA & UTILITÁRIOS",
    "reacao": "🎮 JOGOS INTERATIVOS NO CHAT",
    "rebaixartodos": "👥 GESTÃO DE MEMBROS & MODERAÇÃO",
    "rebirth": "🏹 CAÇA, MASMORRAS & BATALHAS",
    "reddit": "📥 DOWNLOADS, MÍDIAS & FILTROS",
    "reencarnar": "🏹 CAÇA, MASMORRAS & BATALHAS",
    "regex": "👨‍💻 DEV HUB & FERRAMENTAS",
    "rejeitar": "🛡️ ADMINISTRAÇÃO & SEGURANÇA",
    "reliquia": "👑 RELÍQUIAS, MANDAMENTOS & ARCANJOS",
    "rep": "🏆 PERFIL & ECONOMIA",
    "restringir": "🛡️ ADMINISTRAÇÃO & SEGURANÇA",
    "rifa": "🎰 CASSINO, LOTERIAS & APOSTAS",
    "rir": "💖 AFETO & CARINHO",
    "roadmap": "👨‍💻 DEV HUB & FERRAMENTAS",
    "roleta": "🎰 CASSINO, LOTERIAS & APOSTAS",
    "roletarussa": "♟️ TABULEIRO & CLÁSSICOS",
    "roubar": "🏆 PERFIL & ECONOMIA",
    "rpg": "ℹ️ INFORMAÇÕES RÁPIDAS & ATALHOS",
    "runas": "👑 RELÍQUIAS, MANDAMENTOS & ARCANJOS",
    "sair": "🎖️ SERVIDOR VPS, COMANDOS & SEGURANÇA",
    "sc": "🌐 DOWNLOAD UNIVERSAL & STREAMING",
    "search": "🔍 PESQUISA, IA & UTILITÁRIOS",
    "sepia": "🎨 FILTROS, CANVAS & FIGURINHAS",
    "setbotname": "🎖️ SERVIDOR VPS, COMANDOS & SEGURANÇA",
    "setcookies": "🎖️ SERVIDOR VPS, COMANDOS & SEGURANÇA",
    "setdesc": "🛡️ ADMINISTRAÇÃO & SEGURANÇA",
    "setdono": "🎖️ SERVIDOR VPS, COMANDOS & SEGURANÇA",
    "setfotogrupo": "⚙️ EDIÇÃO & SEGURANÇA AVANÇADA",
    "setmenuname": "🎖️ SERVIDOR VPS, COMANDOS & SEGURANÇA",
    "setnomegrupo": "🛡️ ADMINISTRAÇÃO & SEGURANÇA",
    "setwallpaper": "👑 DONOS, VPS & ALUGUEL",
    "ship": "♟️ TABULEIRO & CLÁSSICOS",
    "shop": "💰 ECONOMIA, BANCO & BOLSA",
    "shutdown": "🎖️ SERVIDOR VPS, COMANDOS & SEGURANÇA",
    "signo": "🔍 PESQUISA, IA & UTILITÁRIOS",
    "signocompatibilidade": "🎮 JOGOS INTERATIVOS NO CHAT",
    "simi": "🔍 PESQUISA, IA & UTILITÁRIOS",
    "slayer": "🏹 CAÇA, MASMORRAS & BATALHAS",
    "slowmode": "🛡️ ADMINISTRAÇÃO & SEGURANÇA",
    "solicitacoes": "📋 SOLICITAÇÕES & ENTRADA",
    "sorteio": "♟️ TABULEIRO & CLÁSSICOS",
    "sorteioavancado": "👥 GESTÃO DE MEMBROS & MODERAÇÃO",
    "soundcloud": "📥 DOWNLOADS, MÍDIAS & FILTROS",
    "sp": "🌐 DOWNLOAD UNIVERSAL & STREAMING",
    "speedtest": "👨‍💻 DEV HUB & FERRAMENTAS",
    "spotify": "📥 DOWNLOADS, MÍDIAS & FILTROS",
    "status": "🏓 CONEXÃO & LATÊNCIA",
    "stop": "🎮 JOGOS INTERATIVOS NO CHAT",
    "sysinfo": "🏓 CONEXÃO & LATÊNCIA",
    "tabelafipe": "🔍 PESQUISA, IA & UTILITÁRIOS",
    "tagall": "👥 GESTÃO DE MEMBROS & MODERAÇÃO",
    "take": "📥 DOWNLOADS, MÍDIAS & FILTROS",
    "tarot": "👑 RELÍQUIAS, MANDAMENTOS & ARCANJOS",
    "termo": "🎲 DIVERSÃO & JOGOS",
    "tesouro": "👑 RELÍQUIAS, MANDAMENTOS & ARCANJOS",
    "tesourocoletivo": "🏆 PERFIL & ECONOMIA",
    "tiktok": "📥 DOWNLOADS, MÍDIAS & FILTROS",
    "timestamp": "👨‍💻 DEV HUB & FERRAMENTAS",
    "titulos": "👑 RELÍQUIAS, MANDAMENTOS & ARCANJOS",
    "toimg": "🎨 FILTROS, CANVAS & FIGURINHAS",
    "topativos": "👥 GESTÃO DE MEMBROS & MODERAÇÃO",
    "topcoins": "📊 STATUS & CLASSIFICAÇÃO",
    "torneio": "⚔️ RPG & COMBATES",
    "totalcomandos": "ℹ️ INFORMAÇÕES RÁPIDAS & ATALHOS",
    "trabalhar": "💰 ECONOMIA, BANCO & BOLSA",
    "traduzir": "🔍 PESQUISA, IA & UTILITÁRIOS",
    "triggered": "🎨 FILTROS, CANVAS & FIGURINHAS",
    "tts": "📥 DOWNLOADS, MÍDIAS & FILTROS",
    "twitter": "📥 DOWNLOADS, MÍDIAS & FILTROS",
    "unbancmd": "🎖️ SERVIDOR VPS, COMANDOS & SEGURANÇA",
    "upgrade": "🏹 CAÇA, MASMORRAS & BATALHAS",
    "uuid": "🛠️ FERRAMENTAS DEV & CRIPTOGRAFIA",
    "validador": "👨‍💻 DEV HUB & FERRAMENTAS",
    "velha": "♟️ TABULEIRO & CLÁSSICOS",
    "vender": "🏆 PERFIL & ECONOMIA",
    "verdadeouconsequencia": "🎮 JOGOS INTERATIVOS NO CHAT",
    "voceprefere": "🎮 JOGOS INTERATIVOS NO CHAT",
    "votacao": "🛡️ ADMINISTRAÇÃO & SEGURANÇA",
    "voteban": "🛡️ ADMINISTRAÇÃO & SEGURANÇA",
    "votekick": "🛡️ ADMINISTRAÇÃO & SEGURANÇA",
    "voz": "🌐 DOWNLOAD UNIVERSAL & STREAMING",
    "wallpaperanime": "🎨 FILTROS, CANVAS & FIGURINHAS",
    "wanted": "📥 DOWNLOADS, MÍDIAS & FILTROS",
    "warn": "🛡️ ADMINISTRAÇÃO & SEGURANÇA",
    "wasted": "🎨 FILTROS, CANVAS & FIGURINHAS",
    "welcome": "🛡️ ADMINISTRAÇÃO & SEGURANÇA",
    "whois": "👨‍💻 DEV HUB & FERRAMENTAS",
    "wiki": "🔍 PESQUISA, IA & UTILITÁRIOS",
    "xadrez": "♟️ TABULEIRO & CLÁSSICOS",
    "youtube": "📥 DOWNLOADS, MÍDIAS & FILTROS",
    "yt": "🌐 DOWNLOAD UNIVERSAL & STREAMING",
    "ytmp3": "📥 DOWNLOADS, MÍDIAS & FILTROS",
    "ytmp4": "📥 DOWNLOADS, MÍDIAS & FILTROS",
}
